### ISSUE TITLE
Node module checksum changed

### ISSUE THREAD

**Issue by HaberkornJonas** [axians/meta-microservicebus#30]
Hello,

### Context:
**Poky version**: warrior
**Branch used**: warrior

### Description
Looks like something changed with the license file of the fast-json-stable-stringify node module. This leads to build failure of the microservicebus-node-2.0.8 recipe as it cannot validate the checksum.

![Checksum_build_issue](https://user-images.githubusercontent.com/36864574/72531520-ef91ef80-3871-11ea-8b49-19348ab6bd2f.png)

### Possible solution
Updating the checksum in the recipe solved the issue for me.

**Comment by jonaskgandersson** [comment]
Hi
Thanks for your post.

It is correct that the license file have changed. The copyright have changed.
I have updated thud branch but missed warrior, will update warrior this week as well.
