### ISSUE TITLE
u-boot does not work on emmc?

### ISSUE THREAD

**Issue by amod-amatya** [axians/meta-microservicebus#37]
Have you tried this on emmc on raspberrypi?
It works fine for sdcard but u-boot does not seem to work for emmc?

**Comment by wmmihaa** [comment]
What board/device are you running on (RPI does not have emmc)?

**Comment by jonaskgandersson** [comment]
It is only tested with SD-card, curious what board/solution you are running that support emmc for raspberry pi?
U-boot is configured to support rootfs A/B tougher with RAUC. To add support for other storages you at least need to change the rootfs locations in u-boot init script and RAUC conf.

**Comment by amod-amatya** [comment]
Hy @wmmihaa and @jonaskgandersson thanks for the response.
I am using [revolution pi connect+](https://revolution.kunbus.com/revolution-pi-series/) which is basically a Raspberry Pi Compute module. It does not have a sd card, only emmc.
I have tested it with raspberrypi 3B, everything works absolutely fine. To dig into the basic root of the problem, I starting testing by building a rpi-basic-image which works fine on both raspberrypi and revpi(rasperrypi compute module), but now I added this line **RPI_USE_U_BOOT = "1"** and seems like revpi is not supporting uboot. Since revpi does not have a serial console, I cannot see any boot logs. However, it does have a microhdmi to hdmi cable which i connected but then again a blank screen.
I have seen such problem in the [forum](https://www.raspberrypi.org/forums/viewtopic.php?t=217897) as well but without any solution. I know this might not be the appropriate issue to create for this repo, but then I was out of option and just wanted to know if you guys faced such issue

**Comment by jonaskgandersson** [comment]
I can think of two thing I would look into:
1. How the rpi boot loader loads u-boot, since u-boot normally is located in SD-card, I can't remember of the top of my head where this config is located in meta-raspberrypi. 
1. You have to overload the [boot.cmd](recipes-bsp/rpi-u-boot-scr/files/boot.cmd.in) file with an appropriate one for your device.

You can search meta-rasperrypi files for "RPI_USE_U_BOOT" to se where they change behaviour depending on u-boot.

**Comment by amod-amatya** [comment]
@jonaskgandersson I will definitely try out your suggestions.
