### ISSUE TITLE
Update Yocto images to Krikstone

### ISSUE THREAD

**Issue by wmmihaa** [axians/meta-microservicebus#50]
|Complete| Recipe | Move to layer| Comment |
|-----------------------|-----------------------------------------------------|-------------|-----------|
| :heavy_check_mark: | meta-microservicebus-quintus								|Repo||
| :heavy_check_mark: | bblayers.conf 								|intel-quintus||
| :heavy_check_mark: | local.conf 								|intel-quintus|Skapade en tom för att kunna bygga recipies|
|  :heavy_check_mark:  | conf 								|intel-quintus||
|  :heavy_check_mark:  |~~wic~~									|~~intel-quintus~~|~~Bara aaeon-grub-bootdisk-microcode.wks.in och image-installer.wks.in~~ Use original wic from meta-intel|
|  :heavy_check_mark:  |recipes-core/initrdscripts					|intel-quintus |Kontollera att det funkar, använd custom för aaeon|
| :heavy_check_mark: |recipes-kernel							|intel-quintus||
| :heavy_minus_sign: |recipes-bsp							|intel-nuc	  |Kolla variabler|
| :heavy_minus_sign: |recipes-core/base-files					|intel-nuc	  |kolla var vi ska ha dot.bashrc|
| :heavy_minus_sign: |recipes-core/bundles						|intel-nuc	  ||
| :heavy_minus_sign: |recipe-core/intel-nuc-init					|intel-nuc	  |Kolla att vi inte gör denna I aaeon|
| :heavy_minus_sign: |recipe-core/rauc							|intel-nuc	  ||
| :heavy_minus_sign: |recipes-containers						|intel-nuc	  ||
| :heavy_check_mark: |recipe-core/intel-aaeon-init					|intel-quintus|Byt namn till intel-quintus-init|
| :heavy_check_mark: |recipe-core/intel-aaeon-watchdog				|intel-quintus|Byt namn till intel-quintus-watchdog|	
| :heavy_check_mark: |recipes-extended/cronie					|intel-quintus||
| :heavy_check_mark: |recipes-extended/watchdog					|intel-quintus||
| :heavy_check_mark: |meta-quintus-kiosk/recipes-graphics/openbox		|intel-quintus|Flytta in till meta-microservicebus-quintus|	
| :heavy_check_mark: |meta-quintus-kiosk/recipes-graphics/stalonetray	|intel-quintus|Flytta in till meta-microservicebus-quintus|	
|  :heavy_check_mark: |meta-quintus-kiosk/recipes-graphics/surf			|intel-quintus|Flytta in till meta-microservicebus-quintus|
| :heavy_check_mark:|meta-quintus-kiosk/recipes-graphics/x11vnc		|intel-quintus|Flytta in till meta-microservicebus-quintus|

**Comment by jonaskgandersson** [comment]
Pushat till meta-microservicebus-quintus
